//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumorTaskforce_Research
{
    using System;
    using System.Collections.Generic;
    
    public partial class applied_treatments
    {
        public long AppliedTreatments_ID { get; set; }
        public long Patient_ID { get; set; }
        public long GlobalTreatment_ID { get; set; }
        public System.DateTime Date { get; set; }
        public long Effect { get; set; }
    
        public virtual treatment treatment { get; set; }
        public virtual patient patient { get; set; }
    }
}
