//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumorTaskforce_Research
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class healthEntities : DbContext
    {
        public healthEntities()
            : base("name=healthEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<applied_treatments> applied_treatments { get; set; }
        public virtual DbSet<patient> patients { get; set; }
        public virtual DbSet<record> records { get; set; }
        public virtual DbSet<record_type> record_type { get; set; }
        public virtual DbSet<record_entry> record_entry { get; set; }
        public virtual DbSet<treatment> treatments { get; set; }
    }
}
