//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TumorTaskforce_Research
{
    using System;
    using System.Collections.Generic;
    
    public partial class record_entry
    {
        public long RecordEntry_ID { get; set; }
        public long Record_ID { get; set; }
        public string Entry { get; set; }
        public System.DateTime Date { get; set; }
        public string Notes { get; set; }
    
        public virtual record record { get; set; }
    }
}
